name: Render and Deploy All Quarto Documents

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
    steps:
    - name: Checkout repository 2
      uses: actions/checkout@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("rmarkdown", "ggplot2", "remotes"))'
        Rscript -e 'remotes::install_github("tensorchiefs/data", subdir = "R/edudat", auth_token = Sys.getenv("GITHUB_PAT"), dependencies = TRUE, upgrade = "always", verbose = TRUE)'

    - name: Render test.qmd document
      run: |
        quarto render data/test.qmd --to html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.MY_GITHUB_PAT }}
        publish_dir: ./data
        publish_branch: gh-pages
